version: '3'
services:

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 8080:8080
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DIALECT=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PORT_SERVER=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 8081:8081
    environment:
      - BASE_URL=http://localhost:8080
      - CONTEXT_PATH=todoApp

  nginx: 
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    restart: always

    