name: tests

on: [push, pull_request]
    
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd backend
      - run: npm install
      - run: npm test
        
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd backend
      - run: npm install
      - run: npm test
